project:
  type: website
    
website:
  site-url: https://Hezel2000.github.io/
  # repo-url: https://github.com/archaeothommy/archaeothommy.github.io/
  favicon: favicon.png
  title: "Dominik Hezel"
  navbar:
    left:
      # - text: "My research"
      #   href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

execute:
  freeze: auto